# Generated by Django 5.2.6 on 2025-09-09 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('pants', 'Pants'), ('jacket', 'Jacket'), ('bag', 'Sports Bag'), ('accessory', 'Accessory')], default='jersey', max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('N/A', 'Not Applicable')], default='N/A', max_length=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
